{% set version = "0.17.3" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: hypercorn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hypercorn/hypercorn-{{ version }}.tar.gz
  sha256: 1b37802ee3ac52d2d85270700d565787ab16cf19e1462ccfa9f089ca17574165

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  entry_points:
    - hypercorn = hypercorn.__main__:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8
  run:
    - h11
    - h2 >=3.1.0
    - priority
    - python >=3.8
    - wsproto >=0.14.0
    # below are all py<3.11, but keep for noarch
    - exceptiongroup
    - taskgroup
    - tomli
    - typing_extensions >=3.7.4
  run_constrained:
    # all version pins here, hard deps in outputs
    - aioquic >=0.9.0,<1.0
    - trio >=0.22.0
    - uvloop >=0.18

test:
  requires:
    - pip
  imports:
    - hypercorn
  commands:
    - pip check
    - hypercorn --help

outputs:
  - name: hypercorn

  - name: hypercorn-with-h3
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("hypercorn", max_pin="x.x.x") }}
        - aioquic
    test:
      requires:
        - pip
      imports:
        - hypercorn.protocol.h3
      commands:
        - pip check
        - hypercorn --help

  - name: hypercorn-with-trio
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("hypercorn", max_pin="x.x.x") }}
        - uvloop
    test:
      requires:
        - pip
      imports:
        - hypercorn
      commands:
        - pip check
        - hypercorn --help

  - name: hypercorn-with-uvloop
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("hypercorn", max_pin="x.x.x") }}
        - uvloop
    test:
      requires:
        - pip
      imports:
        - hypercorn.trio
      commands:
        - pip check
        - hypercorn --help

about:
  home: https://github.com/pgjones/hypercorn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A ASGI Server based on Hyper libraries and inspired by Gunicorn.
  description: |
    Hypercorn is an ASGI web server based on the sans-io hyper, h11, h2,
    and wsproto libraries and inspired by Gunicorn. Hypercorn supports HTTP/1, HTTP/2,
    and websockets and the ASGI 2 specification. Hypercorn can utilise asyncio,
    uvloop, or trio worker types.
  doc_url: https://hypercorn.readthedocs.io

extra:
  recipe-maintainers:
    - maxyme
    - dhirschfeld
    - synapticarbors
    - bollwyvl
